export const products = [
    {
      id: 1,
      hero: "/products/illuminator.webp",
      gallery: [
        "/products/illuminator.webp",
        "/products/modulocompleto.jpeg",
        "/products/poweririll.png",
      ],
      image: "/products/illuminator.webp",
      translationKey: "irill",
      certifications: ["DO-178 DAL B"],
    },
    {
      id: 2,
      translationKey: "nozzle",
      hero: "/products/nozzle.webp",
      gallery: [
        "/products/nozzle1.webp",
        "/products/nozzle2.webp",
      ],
      image: "/products/nozzle.webp",
      certifications: ["DO-178 DAL C"],
    },
    {
      id: 3,
      translationKey: "encoder",
      hero: "/products/encoder.webp",
      gallery: [
        "/products/encoder.webp",
        "/products/encoder1.webp",
      ],
      image: "/products/encoder.webp",
      certifications: ["DO-178", "DO-254"],
    },
    // {
    //   id: 4,
    //   title: "Radiation",
    //   subtitle: "Sistema de Protección",
    //   hero: "/products/radiation.jpg",
    //   gallery: [
    //     "/products/radiation1.jpg",
    //     "/products/radiation2.jpg",
    //   ],
    //   image: "/products/radiation.jpg",
    //   description: "El Precision Radiation Thermometer (PRT) es un sistema de medida térmica de alta precisión basado en tecnología de termometría infrarroja, diseñado para la adquisición de temperatura superficial en tiempo real sin contacto físico. El modelo PRT01F permite la medición continua de la temperatura de la superficie del mar durante operaciones aéreas, proporcionando datos fiables incluso en entornos marítimos exigentes. El sistema integra capacidades de control remoto, permitiendo al operador solicitar bajo demanda la transmisión de mediciones térmicas y estados operativos del equipo. El PRT01F está siendo actualmente integrado en distintos programas C-295 VIMAR (Vigilancia Marítima), donde contribuye a misiones de patrulla, monitorización ambiental y apoyo a operaciones de seguridad marítima, cumpliendo con los requisitos de fiabilidad y disponibilidad propios de plataformas de misión crítica.",
    //   certifications: ["DO-178 DAL C", "MIL-STD-883"],
    // },
    {
      id: 5,
      translationKey: "dcd",
      hero: "/products/dimming.webp",
      gallery: [
        "/products/dimming1.webp",
        "/products/dimming.webp",
      ],
      image: "/products/dimming.webp",
      certifications: ["DO-178 DAL C"],
    },
    {
      id: 6,
      translationKey: "pod",
      hero: "/products/POD.webp",
      gallery: [
        "/products/POD1.webp",
        "/products/POD.webp",
      ],
      image: "/products/POD.webp",
      certifications: ["DO-178 DAL C", "MIL-STD-883"],
    },
    {
      id: 7,
      translationKey: "heis",
      hero: "/products/heis.webp",
      gallery: [
        "/products/heis3.webp",
        "/products/heis4.webp",
        "/products/hose.webp",
      ],
      video: "/products/heis.mp4",
      image: "/products/heis3.webp",
       certifications: ["DO-178 DAL C", "MIL-STD-883"],
    },
    {
      id: 8,
      translationKey: "fru",
      hero: "/products/fru.jpg",
      gallery: [
        "/products/fru.jpg",
      ],
      image: "/products/fru.jpg",
      certifications: ["DO-178", "MIL-STD-883"],
    },
    {
      id: 9,
      translationKey: "glasses",
      hero: "/products/3dglasses.png", 
      gallery: [
        "/products/3dglasses.png",
        "/products/3dglasses.jpg",
      ],
      image: "/products/3dglasses.jpg",
      certifications: ["DO-160"], 
    },
    {
      id: 10,
      translationKey: "module",
      hero: "/products/irill2.jpeg", 
      gallery: [
        "/products/irill.jpeg",
        "/products/irill2.jpeg",
        "/products/modulocompleto.jpeg",
      ],
      image: "/products/irill2.jpeg",
      certifications: ["DO-160"], 
    },
    {
      id: 11,
      translationKey: "powercable",
      hero: "/products/powercable2.jpeg", 
      gallery: [
        "/products/powercable2.jpeg",
        "/products/poweririll.png",       
        "/products/irilpower.png",       
      ],
      image: "/products/powercable2.jpeg",
      description:"El Power Control Cable es el enlace eléctrico y de comunicaciones entre el Módulo de Control y el Iluminador. Diseñado para entornos aeronáuticos exigentes, transmite tanto la alimentación como las señales de control necesarias para el funcionamiento del sistema. ",
      certifications: ["DO-160"], 
    },
    {
      id: 12,
      translationKey: "focus",
      hero: "/products/focus.jpeg", 
      gallery: [
        "/products/focus.jpeg",
        "/products/focus2.jpeg",
      ],
      image: "/products/focus2.jpeg",
      certifications: ["DO-160"], 
    },
    {
      id: 13,
      translationKey: "opticalfiber",
      hero: "/products/fibercable.jpeg", 
      gallery: [
        "/products/fibercable.jpeg",
      ],
      image: "/products/fibercable.jpeg",
      certifications: ["DO-160"], 
    },
    {
      id: 14,
      translationKey: "mirror",
      hero: "/products/mirror2.jpeg", 
      gallery: [
        "/products/mirror2.jpeg",
        "/products/mirror.jpeg",
      ],
      image: "/products/mirror2.jpeg",
      certifications: ["DO-160"], 
    },
  ];